package com.clipsync.app.ime

object PinyinCandidateEngine {

    private val candidatesByPinyin: Map<String, List<String>> = mapOf(
        "a" to listOf("啊", "阿", "呵"),
        "ai" to listOf("爱", "矮", "挨", "哎"),
        "an" to listOf("安", "按", "案", "俺"),
        "ba" to listOf("把", "吧", "八", "爸"),
        "bai" to listOf("白", "百", "拜"),
        "ban" to listOf("办", "半", "班", "版"),
        "bang" to listOf("帮", "棒", "绑"),
        "bao" to listOf("包", "报", "保", "宝"),
        "bei" to listOf("被", "北", "倍", "备"),
        "ben" to listOf("本", "奔"),
        "bi" to listOf("比", "必", "笔", "闭"),
        "bian" to listOf("边", "变", "便", "编"),
        "bie" to listOf("别"),
        "bing" to listOf("并", "病", "兵"),
        "bo" to listOf("不", "波", "播"),
        "bu" to listOf("不", "部", "步"),
        "ca" to listOf("擦"),
        "cai" to listOf("才", "菜", "猜"),
        "can" to listOf("参", "残"),
        "cang" to listOf("藏", "仓"),
        "cao" to listOf("草", "操"),
        "ce" to listOf("测", "册"),
        "ceng" to listOf("层"),
        "cha" to listOf("查", "差", "茶", "插"),
        "chai" to listOf("拆", "柴"),
        "chan" to listOf("产", "单", "缠"),
        "chang" to listOf("长", "常", "唱", "场"),
        "chao" to listOf("超", "朝", "吵"),
        "che" to listOf("车", "彻"),
        "chen" to listOf("陈", "沉", "晨"),
        "cheng" to listOf("成", "程", "城", "称"),
        "chi" to listOf("吃", "持", "迟"),
        "chong" to listOf("充", "冲", "重"),
        "chou" to listOf("抽", "丑", "愁"),
        "chu" to listOf("出", "处", "初"),
        "chuang" to listOf("窗", "床", "创"),
        "ci" to listOf("此", "次", "词"),
        "cong" to listOf("从", "聪"),
        "cuo" to listOf("错"),
        "da" to listOf("大", "打", "答", "达"),
        "dai" to listOf("带", "代", "待"),
        "dan" to listOf("但", "单", "担", "蛋"),
        "dang" to listOf("当", "党", "挡"),
        "dao" to listOf("到", "道", "倒", "导"),
        "de" to listOf("的", "得", "德"),
        "deng" to listOf("等", "灯", "登"),
        "di" to listOf("地", "第", "低", "的"),
        "dian" to listOf("点", "电", "店", "典"),
        "ding" to listOf("定", "顶"),
        "dong" to listOf("东", "动", "懂"),
        "dou" to listOf("都", "斗", "豆"),
        "du" to listOf("度", "读", "独", "都"),
        "dui" to listOf("对", "队"),
        "duo" to listOf("多", "夺"),
        "e" to listOf("饿", "额", "俄"),
        "en" to listOf("嗯", "恩"),
        "er" to listOf("而", "二", "儿"),
        "fa" to listOf("发", "法"),
        "fan" to listOf("反", "饭", "翻"),
        "fang" to listOf("方", "放", "房"),
        "fei" to listOf("非", "飞", "费"),
        "fen" to listOf("分", "份", "粉"),
        "feng" to listOf("风", "封", "丰"),
        "fo" to listOf("佛"),
        "fou" to listOf("否"),
        "fu" to listOf("服", "复", "福", "父"),
        "gai" to listOf("该", "改", "概"),
        "gan" to listOf("干", "感", "赶"),
        "gang" to listOf("刚", "港", "钢"),
        "gao" to listOf("高", "告", "搞"),
        "ge" to listOf("个", "各", "歌", "格"),
        "gei" to listOf("给"),
        "gen" to listOf("跟", "根"),
        "geng" to listOf("更", "耕"),
        "gong" to listOf("工", "公", "共", "功"),
        "gou" to listOf("够", "构", "狗"),
        "gu" to listOf("古", "故", "顾"),
        "gua" to listOf("挂", "瓜"),
        "guan" to listOf("关", "管", "观"),
        "guang" to listOf("光", "广"),
        "gui" to listOf("贵", "归", "鬼"),
        "guo" to listOf("国", "过", "果"),
        "ha" to listOf("哈"),
        "hai" to listOf("还", "海", "害"),
        "han" to listOf("汉", "汗", "喊"),
        "hang" to listOf("行", "航"),
        "hao" to listOf("好", "号", "毫", "浩"),
        "he" to listOf("和", "喝", "合", "河"),
        "hen" to listOf("很", "狠"),
        "hong" to listOf("红", "宏", "洪"),
        "hou" to listOf("后", "候", "厚"),
        "hu" to listOf("湖", "户", "护", "呼"),
        "hua" to listOf("话", "花", "化", "华"),
        "huan" to listOf("还", "换", "欢"),
        "huang" to listOf("黄", "皇", "慌"),
        "hui" to listOf("会", "回", "灰", "汇"),
        "huo" to listOf("或", "活", "火"),
        "ji" to listOf("机", "几", "级", "记", "集"),
        "jia" to listOf("家", "加", "价", "假"),
        "jian" to listOf("见", "建", "间", "件"),
        "jiang" to listOf("将", "讲", "江", "降"),
        "jiao" to listOf("叫", "教", "角", "交"),
        "jie" to listOf("接", "节", "界", "解"),
        "jin" to listOf("进", "今", "近", "金"),
        "jing" to listOf("经", "京", "景", "静"),
        "jiu" to listOf("就", "九", "久"),
        "ju" to listOf("就", "句", "局", "具"),
        "jue" to listOf("觉", "决", "绝"),
        "jun" to listOf("军", "均"),
        "kai" to listOf("开", "凯"),
        "kan" to listOf("看", "刊"),
        "kao" to listOf("考", "靠"),
        "ke" to listOf("可", "科", "客", "课"),
        "kong" to listOf("空", "控"),
        "kuai" to listOf("快", "块"),
        "la" to listOf("啦", "拉"),
        "lai" to listOf("来", "赖"),
        "lan" to listOf("兰", "蓝", "栏"),
        "lang" to listOf("浪", "郎"),
        "lao" to listOf("老", "劳"),
        "le" to listOf("了", "乐"),
        "lei" to listOf("类", "累", "雷"),
        "li" to listOf("里", "理", "力", "立", "例"),
        "lian" to listOf("连", "脸", "练", "联"),
        "liang" to listOf("两", "量", "亮", "良"),
        "liao" to listOf("了", "料", "聊"),
        "lin" to listOf("林", "临"),
        "ling" to listOf("领", "令", "零", "灵"),
        "liu" to listOf("六", "流", "留"),
        "long" to listOf("龙", "隆", "弄"),
        "lou" to listOf("楼", "漏"),
        "lu" to listOf("路", "录", "陆"),
        "lv" to listOf("绿", "旅", "率"),
        "ma" to listOf("吗", "妈", "马", "嘛"),
        "mai" to listOf("买", "卖", "麦"),
        "man" to listOf("慢", "满", "曼"),
        "mang" to listOf("忙", "芒"),
        "mao" to listOf("毛", "猫", "贸"),
        "me" to listOf("么"),
        "mei" to listOf("没", "每", "美", "妹"),
        "men" to listOf("们", "门"),
        "meng" to listOf("梦", "蒙"),
        "mi" to listOf("米", "迷", "密"),
        "mian" to listOf("面", "免", "棉"),
        "ming" to listOf("名", "明", "命"),
        "mo" to listOf("摸", "模", "末", "默"),
        "mu" to listOf("目", "母", "木"),
        "na" to listOf("那", "哪", "拿", "呢"),
        "nai" to listOf("乃", "奶"),
        "nan" to listOf("南", "难", "男"),
        "nao" to listOf("脑", "闹"),
        "ne" to listOf("呢"),
        "nei" to listOf("内"),
        "neng" to listOf("能"),
        "ni" to listOf("你", "呢", "尼", "泥"),
        "nian" to listOf("年", "念", "粘"),
        "nin" to listOf("您"),
        "ning" to listOf("宁", "凝"),
        "niu" to listOf("牛", "扭"),
        "nong" to listOf("农", "弄"),
        "nu" to listOf("努", "怒"),
        "nv" to listOf("女"),
        "o" to listOf("哦"),
        "ou" to listOf("欧", "偶"),
        "pa" to listOf("怕", "爬"),
        "pai" to listOf("派", "排"),
        "pan" to listOf("盘", "判"),
        "pang" to listOf("旁", "胖"),
        "pao" to listOf("跑", "泡"),
        "pei" to listOf("配", "陪"),
        "peng" to listOf("朋", "碰"),
        "pi" to listOf("批", "皮", "匹"),
        "pian" to listOf("片", "篇", "偏"),
        "piao" to listOf("票", "漂"),
        "pin" to listOf("拼", "品"),
        "ping" to listOf("平", "评", "瓶"),
        "po" to listOf("破", "坡"),
        "pu" to listOf("普", "铺"),
        "qi" to listOf("起", "其", "气", "期", "器"),
        "qian" to listOf("前", "钱", "千", "签"),
        "qiang" to listOf("强", "枪", "墙"),
        "qiao" to listOf("桥", "敲", "巧"),
        "qie" to listOf("切", "且"),
        "qin" to listOf("亲", "勤", "琴"),
        "qing" to listOf("请", "情", "青", "清"),
        "qiu" to listOf("求", "球", "秋"),
        "qu" to listOf("去", "区", "取", "曲"),
        "quan" to listOf("全", "权", "圈"),
        "que" to listOf("却", "缺"),
        "qun" to listOf("群"),
        "ran" to listOf("然", "燃"),
        "rang" to listOf("让", "嚷"),
        "re" to listOf("热"),
        "ren" to listOf("人", "认", "任"),
        "ri" to listOf("日"),
        "rong" to listOf("容", "荣"),
        "ru" to listOf("如", "入"),
        "ruan" to listOf("软"),
        "rui" to listOf("瑞"),
        "ruo" to listOf("若"),
        "sa" to listOf("撒"),
        "sai" to listOf("赛"),
        "san" to listOf("三", "散"),
        "sao" to listOf("扫"),
        "se" to listOf("色"),
        "sha" to listOf("啥", "杀", "沙"),
        "shan" to listOf("山", "闪", "善"),
        "shang" to listOf("上", "商", "伤"),
        "shao" to listOf("少", "烧"),
        "she" to listOf("设", "社", "蛇"),
        "shen" to listOf("什", "深", "神", "身"),
        "sheng" to listOf("生", "声", "省", "胜"),
        "shi" to listOf("是", "时", "事", "使", "十"),
        "shou" to listOf("手", "收", "受"),
        "shu" to listOf("书", "数", "树", "输"),
        "shui" to listOf("水", "谁"),
        "shuo" to listOf("说", "硕"),
        "si" to listOf("四", "思", "死"),
        "song" to listOf("送", "松"),
        "sou" to listOf("搜"),
        "su" to listOf("苏", "诉", "素"),
        "suan" to listOf("算"),
        "sui" to listOf("随", "岁", "虽"),
        "suo" to listOf("所", "锁"),
        "ta" to listOf("他", "她", "它", "塔"),
        "tai" to listOf("太", "台"),
        "tan" to listOf("谈", "探", "坦"),
        "tang" to listOf("唐", "堂", "糖"),
        "tao" to listOf("套", "讨", "桃"),
        "te" to listOf("特"),
        "teng" to listOf("疼"),
        "ti" to listOf("体", "提", "题", "替"),
        "tian" to listOf("天", "田", "填"),
        "tiao" to listOf("条", "跳"),
        "ting" to listOf("听", "停", "庭"),
        "tong" to listOf("同", "通", "痛"),
        "tou" to listOf("头", "投"),
        "tu" to listOf("图", "土", "途"),
        "tui" to listOf("推", "退"),
        "tuo" to listOf("托", "脱"),
        "wa" to listOf("哇", "瓦", "挖"),
        "wai" to listOf("外"),
        "wan" to listOf("万", "完", "晚", "玩"),
        "wang" to listOf("网", "王", "望", "往"),
        "wei" to listOf("为", "位", "未", "维", "微"),
        "wen" to listOf("问", "文", "闻"),
        "wo" to listOf("我", "握", "窝"),
        "wu" to listOf("无", "五", "物", "务", "误"),
        "xi" to listOf("喜", "系", "西", "息", "希"),
        "xia" to listOf("下", "夏", "吓"),
        "xian" to listOf("先", "现", "线", "显"),
        "xiang" to listOf("想", "向", "像", "相"),
        "xiao" to listOf("小", "笑", "校", "消"),
        "xie" to listOf("写", "些", "谢", "协"),
        "xin" to listOf("新", "心", "信", "辛"),
        "xing" to listOf("行", "性", "型", "兴"),
        "xiong" to listOf("兄", "雄"),
        "xiu" to listOf("修", "秀"),
        "xu" to listOf("许", "需", "续"),
        "xuan" to listOf("选", "宣", "旋"),
        "xue" to listOf("学", "雪", "血"),
        "xun" to listOf("寻", "讯", "迅"),
        "ya" to listOf("呀", "压", "亚"),
        "yan" to listOf("眼", "言", "验", "烟"),
        "yang" to listOf("样", "阳", "养", "杨"),
        "yao" to listOf("要", "摇", "药"),
        "ye" to listOf("也", "页", "夜"),
        "yi" to listOf("一", "已", "以", "意", "议"),
        "yin" to listOf("因", "音", "银", "印"),
        "ying" to listOf("应", "英", "影", "营"),
        "yong" to listOf("用", "永", "勇"),
        "you" to listOf("有", "又", "由", "友"),
        "yu" to listOf("于", "与", "语", "鱼", "雨"),
        "yuan" to listOf("元", "原", "员", "远"),
        "yue" to listOf("月", "越", "约"),
        "yun" to listOf("云", "运"),
        "zai" to listOf("在", "再", "载"),
        "zan" to listOf("咱", "赞"),
        "zao" to listOf("早", "造"),
        "ze" to listOf("则", "责"),
        "zen" to listOf("怎"),
        "zeng" to listOf("曾", "增"),
        "zha" to listOf("炸", "扎", "查"),
        "zhan" to listOf("站", "战", "展"),
        "zhang" to listOf("长", "张", "章", "掌"),
        "zhao" to listOf("找", "照", "着", "招"),
        "zhe" to listOf("这", "着", "者"),
        "zhen" to listOf("真", "针", "镇"),
        "zheng" to listOf("正", "政", "整", "证"),
        "zhi" to listOf("知", "只", "之", "直", "指"),
        "zhong" to listOf("中", "种", "重", "众"),
        "zhou" to listOf("周", "州", "走"),
        "zhu" to listOf("主", "住", "注", "祝"),
        "zhuan" to listOf("转", "专"),
        "zhuang" to listOf("装", "状"),
        "zhui" to listOf("追"),
        "zhun" to listOf("准"),
        "zhuo" to listOf("着", "桌"),
        "zi" to listOf("子", "字", "自"),
        "zong" to listOf("总", "宗"),
        "zou" to listOf("走"),
        "zu" to listOf("组", "足", "族"),
        "zui" to listOf("最", "嘴"),
        "zuo" to listOf("做", "作", "坐", "左"),
        "nihao" to listOf("你好"),
        "xiexie" to listOf("谢谢"),
        "zaijian" to listOf("再见"),
        "women" to listOf("我们"),
        "nimen" to listOf("你们"),
        "tamen" to listOf("他们", "她们", "它们"),
        "zhongguo" to listOf("中国"),
        "renmin" to listOf("人民"),
        "gongzuo" to listOf("工作"),
        "shenghuo" to listOf("生活"),
        "xianzai" to listOf("现在"),
        "jinian" to listOf("今年"),
        "jintian" to listOf("今天"),
        "mingtian" to listOf("明天"),
        "zuotian" to listOf("昨天"),
        "keyi" to listOf("可以"),
        "meiguanxi" to listOf("没关系"),
        "meishenme" to listOf("没什么"),
        "duibuqi" to listOf("对不起"),
        "bukeqi" to listOf("不客气"),
        "zhidao" to listOf("知道"),
        "xihuan" to listOf("喜欢"),
        "gaoxing" to listOf("高兴"),
        "pengyou" to listOf("朋友"),
        "laoshi" to listOf("老师"),
        "xuesheng" to listOf("学生"),
        "shouji" to listOf("手机"),
        "diannao" to listOf("电脑"),
        "wangluo" to listOf("网络"),
        "shurufa" to listOf("输入法")
    )

    private val preferredPhrases = setOf(
        "你好", "谢谢", "再见", "我们", "你们", "他们", "她们", "它们",
        "中国", "人民", "工作", "生活", "现在", "今天", "明天", "昨天",
        "可以", "没关系", "没什么", "对不起", "不客气", "知道", "喜欢",
        "高兴", "朋友", "老师", "学生", "手机", "电脑", "网络", "输入法"
    )

    fun getCandidates(pinyin: String, limit: Int = 12): List<String> {
        if (pinyin.isBlank()) return emptyList()

        val normalized = normalize(pinyin)
        val ranked = linkedMapOf<String, Int>()

        candidatesByPinyin[normalized].orEmpty().forEachIndexed { index, value ->
            val exactScore = 10_000 - index * 20 - preferredPenalty(value)
            ranked.merge(value, exactScore, ::maxOf)
        }

        candidatesByPinyin.asSequence()
            .filter { (key, _) -> key.startsWith(normalized) && key != normalized }
            .forEach { (key, values) ->
                val distancePenalty = (key.length - normalized.length) * 100
                values.forEachIndexed { index, value ->
                    val prefixScore = 5_000 - distancePenalty - index * 15 - preferredPenalty(value)
                    ranked.merge(value, prefixScore, ::maxOf)
                }
            }

        return ranked.entries
            .sortedWith(
                compareByDescending<Map.Entry<String, Int>> { it.value }
                    .thenByDescending { it.key.length }
                    .thenBy { it.key }
            )
            .take(limit)
            .map { it.key }
    }

    private fun preferredPenalty(value: String): Int {
        return if (preferredPhrases.contains(value)) 0 else 300
    }

    private fun normalize(pinyin: String): String {
        return pinyin.lowercase()
            .replace("ü", "v")
            .replace("u:", "v")
    }
}
